### ISSUE TITLE
sensors disappears after HA-updates

### ISSUE THREAD

**Issue by SniperRus** [Kartax/home-assistant-binance#4]
after last HA updates my binance sensors are disappears
my strings in configuration.yaml
```
sensor:
  - platform: binance
    symbols:
      - USDTTRY
```

may I need it to reconfigure it somehow?
