### ISSUE TITLE
Feature Request: Limit decimal places

### ISSUE THREAD

**Issue by acs-lux** [Kartax/home-assistant-binance#5]
Hi,

I couldn't find where to put feature requests but, is it possible to add a value for the number of decimal places to the config?

Something like:

Decimals: 2

**Comment by kirush0280** [comment]
```
type: entities
entities:
  - entity: sensor.binance_ticker_btcusdt
    name: Курс
    type: custom:multiple-entity-row
    show_state: false
    entities:
      - entity: sensor.binance_ticker_btcusdt
        format: precision0
        name: BTC
      - entity: sensor.binance_ticker_ethusdt
        format: precision0
        name: ETH
      - entity: sensor.binance_ticker_etcusdt
        format: precision0
        name: ETC

```
I did it so. Precision0, it means without decimal.
