### ISSUE TITLE
Ticker object graph

### ISSUE THREAD

**Issue by kirush0280** [Kartax/home-assistant-binance#6]
Hello!
Now when I click to price, I see this:
![btc_domain](https://github.com/Kartax/home-assistant-binance/assets/13412942/60abfcc9-b6a2-4210-bfae-688137910ac0)
better, will be if here will be graph.

**Comment by kirush0280** [comment]
Resolved:
[customization.yaml]
```
sensor.binance_ticker_btcusdt:
  state_class: measurement
```

**Comment by torliPL** [comment]
In order to make this modification:
1. Make new file customize.yaml in main config folder.
2. Put inside code:
```
sensor.binance_ticker_btcusdt:
  state_class: measurement
sensor.binance_ticker_ethusdt:
  state_class: measurement
```
3. In configuration.yaml add:
```
homeassistant:
  customize: !include customize.yaml
```
4. From dev tools menu reload configuration.

The result is:
![image](https://github.com/Kartax/home-assistant-binance/assets/75480385/31c86ef5-6b3e-4305-88b1-c90323ec1f55)
